### ISSUE TITLE
Parse error causes server to abort

### ISSUE THREAD

**Issue by hsolbrig** [shexSpec/shex.js#1]
Invocation:

  ./bin/validate --serve http://localhost:4290/validate -x ~/Development/git/crDDI/validator/shex/account.shex --regex-module nfax-val-1err --duplicate-shape replace

When we feed the server a poorly formed ShEx document we get:
```
Error: file:///Users/mrf7578/Development/git/shexSpec/shex.js/rest/uploads/upload_52dbf1bbe6d9bfb0da04075f25e174ad(103): Parse error on line 102:
...cident occurred    see
----------------------^
Expecting '!', 'IRIREF', 'PNAME_NS', '}', '&', '|', '(', ')', '^', 'a', 'PNAME_LN', got 'invalid character s'
...cident occurred    see
----------------------^
    at parseShExC (/Users/mrf7578/Development/git/shexSpec/shex.js/lib/ShExLoader.js:102:54)
    at /Users/mrf7578/Development/git/shexSpec/shex.js/lib/ShExLoader.js:82:9
    at tryCallTwo (/Users/mrf7578/Development/git/shexSpec/shex.js/node_modules/promise/lib/core.js:45:5)
    at doResolve (/Users/mrf7578/Development/git/shexSpec/shex.js/node_modules/promise/lib/core.js:200:13)
    at new Promise (/Users/mrf7578/Development/git/shexSpec/shex.js/node_modules/promise/lib/core.js:66:3)
    at /Users/mrf7578/Development/git/shexSpec/shex.js/lib/ShExLoader.js:81:14
    at /Users/mrf7578/Development/git/shexSpec/shex.js/lib/ShExLoader.js:61:14
    at tryCallOne (/Users/mrf7578/Development/git/shexSpec/shex.js/node_modules/promise/lib/core.js:37:12)
    at /Users/mrf7578/Development/git/shexSpec/shex.js/node_modules/promise/lib/core.js:123:15
    at flush (/Users/mrf7578/Development/git/shexSpec/shex.js/node_modules/asap/raw.js:50:29)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
>
```

**Comment by ericprud** [comment]
Fixed: [moved .catch to bottom](https://github.com/shexSpec/shex.js/commit/a885410dea6e52fddee34aca8cc9f41faea96c31)
