### ISSUE TITLE
Validation failing for shape with only an optional group

### ISSUE THREAD

**Issue by joeltg** [shexSpec/shex.js#65]
I _believe_ that this is a valid shape:
```
PREFIX schema: <http://schema.org/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

start = @_:organization

_:organization bnode {
  a [ schema:Organization ] ;
  ( schema:alumni @_:person ) * ;
}

_:person bnode {
  (
    schema:givenName xsd:string ;
    schema:familyName xsd:string ;
  ) ? ;
}
```

Testing this with
```javascript
const fs = require("fs")
const N3 = require("n3")

const ShExParser = require("@shex/parser")
const ShExCore = require("@shex/core")

const s = fs.readFileSync("test2.shex", "utf8")

const schema = ShExParser.construct().parse(s)
const validator = ShExCore.Validator.construct(schema)

const store = new N3.Store()
new N3.StreamParser({ format: "application/n-quads", blankNodePrefix: "_:" })
  .on("data", quad => store.addQuad(quad))
  .on("end", () => {
    const db = ShExCore.Util.makeN3DB(store)
    const result = validator.validate(db, "_:b0", schema.start)
    console.log(JSON.stringify(result, null, "  "))
  }).end(`
_:b0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://schema.org/Organization> .
_:b0 <http://schema.org/alumni> _:b1 .
_:b1 <http://schema.org/givenName> "Joel" .
_:b1 <http://schema.org/familyName> "Gustafson" .
`)
```
does indeed produce a valid `ShapeAndResults` object, but testing _without_ the last two triples - just
```
_:b0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://schema.org/Organization> .
_:b0 <http://schema.org/alumni> _:b1 .
```
... throws an error:
```
% node test.js
/Users/joel/Projects/pkgm/shex.js/packages/shex-core/lib/regex/threaded-val-nerr.js:346
      if (Object.keys(fromValidatePoint).length > 0) // guard against {}
                 ^

TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at finish (/Users/joel/Projects/pkgm/shex.js/packages/shex-core/lib/regex/threaded-val-nerr.js:346:18)
    at Object.match (/Users/joel/Projects/pkgm/shex.js/packages/shex-core/lib/regex/threaded-val-nerr.js:264:9)
    at ShExValidator_constructor._validateShape (/Users/joel/Projects/pkgm/shex.js/packages/shex-core/lib/ShExValidator.js:609:33)
    at ShExValidator_constructor._validateShapeExpr (/Users/joel/Projects/pkgm/shex.js/packages/shex-core/lib/ShExValidator.js:429:19)
    at ShExValidator_constructor._validateShapeExpr (/Users/joel/Projects/pkgm/shex.js/packages/shex-core/lib/ShExValidator.js:454:24)
    at ShExValidator_constructor.validate (/Users/joel/Projects/pkgm/shex.js/packages/shex-core/lib/ShExValidator.js:393:20)
    at _errorsByShapeLabel (/Users/joel/Projects/pkgm/shex.js/packages/shex-core/lib/ShExValidator.js:502:34)
    at ShExValidator_constructor._errorsMatchingShapeExpr (/Users/joel/Projects/pkgm/shex.js/packages/shex-core/lib/ShExValidator.js:700:24)
    at /Users/joel/Projects/pkgm/shex.js/packages/shex-core/lib/ShExValidator.js:688:26
```

I'm using the latest master (aeef29e77391f4688ebb5ea8a0c995d777e73fd4) with N3 `v1.3.5`.

**Comment by joeltg** [comment]
If I add any other triple constraint to the `_:person` shape - like
```
PREFIX schema: <http://schema.org/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

start = @_:organization

_:organization bnode {
  a [ schema:Organization ] ;
  ( schema:alumni @_:person ) * ;
}

_:person bnode {
  a [ schema:Person ] ;
  (
    schema:givenName xsd:string ;
    schema:familyName xsd:string ;
  ) ? ;
}
```
... then validating
```
_:b0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://schema.org/Organization> .
_:b0 <http://schema.org/alumni> _:b1 .
_:b1 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://schema.org/Person> .
```
passes, as expected.

**Comment by ericprud** [comment]
I hope to get to this over the weekend.

**Comment by ericprud** [comment]
[replicated on rawgit](https://rawgit.com/shexSpec/shex.js/master/packages/shex-webapp/doc/shex-simple.html?schema=PREFIX%20schema%3A%20%3Chttp%3A%2F%2Fschema.org%2F%3E%0APREFIX%20xsd%3A%20%3Chttp%3A%2F%2Fwww.w3.org%2F2001%2FXMLSchema%23%3E%0A%0Astart%20%3D%20%40_%3Aorganization%0A%0A_%3Aorganization%20bnode%20%7B%0A%20%20a%20%5B%20schema%3AOrganization%20%5D%20%3B%0A%20%20(%20schema%3Aalumni%20%40_%3Aperson%20)%20*%20%3B%0A%7D%0A%0A_%3Aperson%20bnode%20%7B%0A%20%20(%0A%20%20%20%20schema%3AgivenName%20xsd%3Astring%20%3B%0A%20%20%20%20schema%3AfamilyName%20xsd%3Astring%20%3B%0A%20%20)%20%3F%20%3B%0A%7D&data=_%3Ab0%20%3Chttp%3A%2F%2Fwww.w3.org%2F1999%2F02%2F22-rdf-syntax-ns%23type%3E%20%3Chttp%3A%2F%2Fschema.org%2FOrganization%3E%20.%0A_%3Ab0%20%3Chttp%3A%2F%2Fschema.org%2Falumni%3E%20_%3Ab1%20.%0A%23_%3Ab1%20%3Chttp%3A%2F%2Fschema.org%2FgivenName%3E%20%22Joel%22%20.%0A%23_%3Ab1%20%3Chttp%3A%2F%2Fschema.org%2FfamilyName%3E%20%22Gustafson%22%20.&manifestURL=..%2Fexamples%2Fmanifest.json&shape-map=_%3Ab0_b0%40START&interface=human&success=proof&regexpEngine=threaded-val-nerr)

**Comment by ericprud** [comment]
this patch fixes your immediate issue, but I've got some related homework (writing tests, implementing in the other regular expression engine) to do before making another release.
``` diff
modified   packages/shex-core/lib/regex/threaded-val-nerr.js
@@ -54,7 +54,15 @@ function vpEngine (schema, shape, index) {
                 });
               }
               if (sub.length === 0 /* min:0 */ || sub[0].errors.length > 0)
-                return repeated < min ? sub : newThreads;
+                return repeated < min ? sub : newThreads.map(
+                  thr =>
+                    Object.assign({}, thr, {
+                      expression: thr.expression || Object.assign({
+                        type: type,
+                        solutions: []
+                      }, minmax)
+                    })
+                );
               else
                 inner = inner.concat(sub);
               // newThreads.expressions.push(sub);
```

**Comment by joeltg** [comment]
Thanks so much! A fix isn't urgent or anything, I just wanted to raised the issue.
